#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2'

volumes:
  datamongo: {}

services:
  nginx:
    image: nginx:1.21.1-alpine
    container_name: gio_am_nginx
    restart: always
    volumes:
      - ./iam/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - management
      - gateway
      - webui

  mongodb:
    image: mongo:4.2
    container_name: gio_am_mongodb
    restart: always
    volumes:
      - datamongo:/data/db
      - ./iam/logs/am-mongodb:/var/log/mongodb

  gateway:
    image: graviteeio/am-gateway:${GIO_AM_VERSION}
    container_name: gio_am_gateway
    restart: always
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./iam/logs/am-gateway:/etc/gravitee.io/log
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000

  management:
    image: graviteeio/am-management-api:${GIO_AM_VERSION}
    container_name: gio_am_management
    restart: always
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./iam/logs/am-management-api:/etc/gravitee.io/log
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000

  webui:
    image: graviteeio/am-management-ui:${GIO_AM_VERSION}
    container_name: gio_am_webui
    restart: always
    depends_on:
      - management
    environment:
      - MGMT_API_URL=http://localhost:8080/am
      - MGMT_UI_URL=http://localhost:8080/am/ui
    volumes:
      - ./iam/logs/am-webui:/var/log/httpd

  microservice_client_php:
    build:
      dockerfile: ./microservice-client/Dockerfile
      target: app_php_dev
    environment:
      IAM_DOMAIN: ${IAM_DOMAIN}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    # volumes:
    #   - ./microservice-client:/srv/app:rw

  microservice_server_php:
    build:
      dockerfile: ./microservice-server/Dockerfile
      target: app_php_dev
    environment:
      IAM_DOMAIN: ${IAM_DOMAIN}
    # volumes:
    #   - ./microservice-server:/srv/app:rw
    ports:
      - 9000

  microservice_server_nginx:
    build:
      dockerfile: ./microservice-server/Dockerfile
      target: app_nginx
    ports:
      - 8000:80

  microservice_server_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: app
      # You should definitely change the password in production
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
    ports:
      - 5485:5432